---
- name: setup personal directories
  file:
    path: /home/{{ user_name }}/{{ item }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    recurse: true
  with_items:
    - bin
    - tmp
    - lib
    - ".lein"
    - ".config/fish"
    - Downloads
  become: false

- apt_key:
    url: https://deb.opera.com/archive.key
    state: present
  become: true

- apt_repository:
    repo: deb https://deb.opera.com/opera-stable/ stable non-free
    state: present
    update_cache: yes
  become: true

- apt_repository:
    repo: deb http://archive.canonical.com/ubuntu bionic partner
    state: present
    update_cache: yes
  become: true

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    install_recommends: yes
  with_items:
    - libgstreamer1.0-dev
    - libncurses5-dev
    - libgnutls28-dev
    - tmux
    - texinfo
    - build-essential
    - automake
    - autoconf
    - git
    - meld
    - fish
    # - opera
  become: true

- name: Install ripgrep
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/0.9.0/ripgrep_0.9.0_amd64.deb
  become: true

- name: get emacs 26 source
  git:
    repo: https://github.com/emacs-mirror/emacs.git
    dest: ~/emacs
    version: emacs-26
  become: false

- name: build emacs 26
  shell: cd ~/emacs && ./autogen.sh && ./configure --without-x && make && sudo make install && make clean
  become: false

- name: checkout my emacs config
  git:
    repo: https://github.com/rjspotter/emacs_config.git
    dest: /home/{{ user_name }}/.emacs.d
  become: false

- name: write custom bash config
  template: src=bashrc.j2 dest=/home/{{ user_name }}/.bashrc owner={{ user_name }}

- name: write custom fish config
  template: src=fish.conf.j2 dest=/home/{{ user_name }}/.config/fish/config.fish owner={{ user_name }}

- name: write custom tmux config
  template: src=tmux.conf.j2 dest=/home/{{ user_name }}/.tmux.conf owner={{ user_name }}

- name: write custom git config
  template: src=gitconfig.j2 dest=/home/{{ user_name }}/.gitconfig owner={{ user_name }}

- name: import lien profile
  template: src=lein_profiles.j2 dest=/home/{{ user_name }}/.lein/profiles.clj mode=0744 owner={{ user_name }}

- name: import psg
  template: src=psg dest=/home/{{ user_name }}/bin/psg mode=0755 owner={{ user_name }}

- name: symlink code
  file:
    src: /vagrant
    dest: /home/{{ user_name }}/code
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: link
  ignore_errors: true
  become: false
  when: vagrant_use_sync

- name: otherwise make code dir
  file:
    path: /home/{{ user_name }}/code
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
  when: not vagrant_use_sync

- name: Install handy scratch files
  file:
    path: /home/{{ user_name }}/tmp/scratch.{{ item }}
    state: touch
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "u=rw,g=r,o=r"
  with_items:
    - ex
    - rb
    - txt
    - json
    - js
    - html
    - ts
    - jl

- name: setup ssh login
  lineinfile:
#    path: /etc/selinux/config
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    regexp: 'rjspotter@wheatley'
    line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCduUqawkxXPozz9dQ7CxZVILcbA0WDmcf+WEipriIOqfc1xxRC9u2bn9MTG0apwUX1Hv4L9G3heJfsiijCpZ7qbEAsMYcwOPxIN/ecfLTA1m9KEWSesv6f0BMWaFRtMXpvuJI8fbYlLkqmHYVkczqaEVgjsuoUbWLa6644yoYDwvrxlTVRfDrZe1MvUxjHQXkpGEr/F70ltHqzke8FCr3FmEl209fjMy6Z5Ewisx7zgqiWAzoTPcsqCPGD0KCu9OrdYdr+CWGpbEzh9kVluKJdiAUwqe7OY9g2D9h8lvPXJGhqI7YcBKl8KnaxloLkqPNX9++gkIGo/iZTG/jGQxX3 rjspotter@wheatley
'

- name: ensure ownage
  shell: chown -R {{ user_name}} /home/{{ user_name }}

- name: ensure groupage
  shell: chgrp -R {{ user_name}} /home/{{ user_name }}
