---
- name: setup personal directories
  file:
    path: /home/{{ remote_user }}/{{ item }}
    state: directory
    # owner: "{{remote_user}}"
    # group: "{{remote_user}}"
    recurse: true
    mode: 0777
  with_items:
    - bin
    - tmp
    - lib
    - code
    - ".lein"
    - ".config/fish"
    - Downloads
  become: false

- name: Install base packages
  apt:
    name: [libgstreamer1.0-dev, libncurses5-dev, libgnutls28-dev, tmux, texinfo, build-essential, automake, autoconf, git, meld, fish, python3-pip]
    state: latest
    update_cache: yes
    install_recommends: yes
  become: true

- name: Install ripgrep
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep_12.0.1_amd64.deb
  become: true

- name: Install vivaldi
  apt:
    deb: https://downloads.vivaldi.com/stable/vivaldi-stable_2.11.1811.49-1_amd64.deb
  become: true

# - name: install pgFormatter # TODO

- name: install pips
  pip:
    name: [virtualenv, jupyterlab, jupyter-console, fastparquet, python-snappy]
    executable: pip-3.3

- name: get emacs 26 source
  git:
    repo: https://github.com/emacs-mirror/emacs.git
    dest: ~/emacs
    version: emacs-26
  become: false

- name: build emacs 26
  shell: cd ~/emacs && ./autogen.sh && ./configure --without-x && make && sudo make install && make clean
  become: false

- name: checkout my emacs config
  git:
    repo: https://github.com/rjspotter/emacs_config.git
    dest: /home/{{ remote_user }}/.emacs.d
  become: false

- name: write custom bash config
  template: src=bashrc.j2 dest=/home/{{ remote_user }}/.bashrc owner={{ remote_user }}

- name: write custom fish config
  template: src=fish.conf.j2 dest=/home/{{ remote_user }}/.config/fish/config.fish owner={{ remote_user }}

- name: write custom tmux config
  template: src=tmux.conf.j2 dest=/home/{{ remote_user }}/.tmux.conf owner={{ remote_user }}

- name: write custom git config
  template: src=gitconfig.j2 dest=/home/{{ remote_user }}/.gitconfig owner={{ remote_user }}

- name: write custom git message
  template: src=gitmessage.j2 dest=/home/{{ remote_user }}/.gitmessage owner={{ remote_user }}

- name: import lien profile
  template: src=lein_profiles.j2 dest=/home/{{ remote_user }}/.lein/profiles.clj mode=0744 owner={{ remote_user }}

- name: import psg
  template: src=psg dest=/home/{{ remote_user }}/bin/psg mode=0755 owner={{ remote_user }}

- name: Install handy scratch files
  file:
    path: /home/{{ remote_user }}/tmp/scratch.{{ item }}
    state: touch
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: "u=rw,g=r,o=r"
  with_items:
    - ex
    - rb
    - txt
    - json
    - js
    - html
    - ts
    - jl
    - scala
    - css
    - sass
    - sql
    - py
  become: false

- name: setup ssh login
  lineinfile:
#    path: /etc/selinux/config
    dest: /home/{{ remote_user }}/.ssh/authorized_keys
    regexp: 'rjspotter@wheatley'
    line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCduUqawkxXPozz9dQ7CxZVILcbA0WDmcf+WEipriIOqfc1xxRC9u2bn9MTG0apwUX1Hv4L9G3heJfsiijCpZ7qbEAsMYcwOPxIN/ecfLTA1m9KEWSesv6f0BMWaFRtMXpvuJI8fbYlLkqmHYVkczqaEVgjsuoUbWLa6644yoYDwvrxlTVRfDrZe1MvUxjHQXkpGEr/F70ltHqzke8FCr3FmEl209fjMy6Z5Ewisx7zgqiWAzoTPcsqCPGD0KCu9OrdYdr+CWGpbEzh9kVluKJdiAUwqe7OY9g2D9h8lvPXJGhqI7YcBKl8KnaxloLkqPNX9++gkIGo/iZTG/jGQxX3 rjspotter@wheatley
'

- name: ensure ownage
  shell: chown -R {{ remote_user}} /home/{{ remote_user }}

- name: ensure groupage
  shell: chgrp -R {{ remote_user}} /home/{{ remote_user }}
