---
- name: write custom bash config
  template: src=bashrc.j2 dest=/home/{{ user_name }}/.bashrc owner={{ user_name }}
- name: write custom tmux config
  template: src=tmux.conf.j2 dest=/home/{{ user_name }}/.tmux.conf owner={{ user_name }}
- name: write custom git config
  template: src=gitconfig.j2 dest=/home/{{ user_name }}/.gitconfig owner={{ user_name }}
- name: Creates private bin directory
  file: path=/home/{{ user_name }}/bin state=directory owner={{ user_name }}
- name: Creates private lib directory
  file: path=/home/{{ user_name }}/lib state=directory owner={{ user_name }}
- name: Creates lein config dir
  file: path=/home/{{ user_name }}/.lein state=directory owner={{ user_name }}
- name: import lien profile
  template: src=lein_profiles.j2 dest=/home/{{ user_name }}/.lein/profiles.clj mode=0744 owner={{ user_name }}
- name: import psg
  template: src=psg dest=/home/{{ user_name }}/bin/psg mode=0755 owner={{ user_name }}
- name: Install base packages
  apt: name={{item}} state=latest
  with_items:
    - tmux
    - texinfo
    - libncurses5-dev
    - build-essential
    - automake
    - autoconf
  become: true
- name: get emacs 25 source
  git:
    repo: https://github.com/emacs-mirror/emacs.git
    dest: ~/emacs
    version: emacs-25
- name: build emacs 25
  shell: cd ~/emacs && ./autogen.sh && ./configure && make && sudo make install && make clean
- name: checkout my emacs config
  git:
    repo: https://github.com/rjspotter/emacs_config.git
    dest: /home/{{ user_name }}/.emacs.d
  become: false
- name: symlink code
  file:
    src: /vagrant
    dest: /home/{{ user_name }}/code
    owner: vagrant
    group: vagrant
    state: link
  ignore_errors: true
  become: false
  when: vagrant_use_sync
